/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AutoResponseService } from "../autoResponse.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AutoResponseCreateInput } from "./AutoResponseCreateInput";
import { AutoResponse } from "./AutoResponse";
import { AutoResponseFindManyArgs } from "./AutoResponseFindManyArgs";
import { AutoResponseWhereUniqueInput } from "./AutoResponseWhereUniqueInput";
import { AutoResponseUpdateInput } from "./AutoResponseUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AutoResponseControllerBase {
  constructor(
    protected readonly service: AutoResponseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AutoResponse })
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAutoResponse(
    @common.Body() data: AutoResponseCreateInput
  ): Promise<AutoResponse> {
    return await this.service.createAutoResponse({
      data: {
        ...data,

        trend: data.trend
          ? {
              connect: data.trend,
            }
          : undefined,

        twitterAccount: data.twitterAccount
          ? {
              connect: data.twitterAccount,
            }
          : undefined,
      },
      select: {
        aiResponse: true,
        content: true,
        createdAt: true,
        id: true,
        mediaUrl: true,

        trend: {
          select: {
            id: true,
          },
        },

        twitterAccount: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AutoResponse] })
  @ApiNestedQuery(AutoResponseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async autoResponses(@common.Req() request: Request): Promise<AutoResponse[]> {
    const args = plainToClass(AutoResponseFindManyArgs, request.query);
    return this.service.autoResponses({
      ...args,
      select: {
        aiResponse: true,
        content: true,
        createdAt: true,
        id: true,
        mediaUrl: true,

        trend: {
          select: {
            id: true,
          },
        },

        twitterAccount: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AutoResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async autoResponse(
    @common.Param() params: AutoResponseWhereUniqueInput
  ): Promise<AutoResponse | null> {
    const result = await this.service.autoResponse({
      where: params,
      select: {
        aiResponse: true,
        content: true,
        createdAt: true,
        id: true,
        mediaUrl: true,

        trend: {
          select: {
            id: true,
          },
        },

        twitterAccount: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AutoResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAutoResponse(
    @common.Param() params: AutoResponseWhereUniqueInput,
    @common.Body() data: AutoResponseUpdateInput
  ): Promise<AutoResponse | null> {
    try {
      return await this.service.updateAutoResponse({
        where: params,
        data: {
          ...data,

          trend: data.trend
            ? {
                connect: data.trend,
              }
            : undefined,

          twitterAccount: data.twitterAccount
            ? {
                connect: data.twitterAccount,
              }
            : undefined,
        },
        select: {
          aiResponse: true,
          content: true,
          createdAt: true,
          id: true,
          mediaUrl: true,

          trend: {
            select: {
              id: true,
            },
          },

          twitterAccount: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AutoResponse })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAutoResponse(
    @common.Param() params: AutoResponseWhereUniqueInput
  ): Promise<AutoResponse | null> {
    try {
      return await this.service.deleteAutoResponse({
        where: params,
        select: {
          aiResponse: true,
          content: true,
          createdAt: true,
          id: true,
          mediaUrl: true,

          trend: {
            select: {
              id: true,
            },
          },

          twitterAccount: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
