/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TwitterAccountService } from "../twitterAccount.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TwitterAccountCreateInput } from "./TwitterAccountCreateInput";
import { TwitterAccount } from "./TwitterAccount";
import { TwitterAccountFindManyArgs } from "./TwitterAccountFindManyArgs";
import { TwitterAccountWhereUniqueInput } from "./TwitterAccountWhereUniqueInput";
import { TwitterAccountUpdateInput } from "./TwitterAccountUpdateInput";
import { AutoResponseFindManyArgs } from "../../autoResponse/base/AutoResponseFindManyArgs";
import { AutoResponse } from "../../autoResponse/base/AutoResponse";
import { AutoResponseWhereUniqueInput } from "../../autoResponse/base/AutoResponseWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TwitterAccountControllerBase {
  constructor(
    protected readonly service: TwitterAccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TwitterAccount })
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTwitterAccount(
    @common.Body() data: TwitterAccountCreateInput
  ): Promise<TwitterAccount> {
    return await this.service.createTwitterAccount({
      data: data,
      select: {
        accessToken: true,
        accessTokenSecret: true,
        accountName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TwitterAccount] })
  @ApiNestedQuery(TwitterAccountFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async twitterAccounts(
    @common.Req() request: Request
  ): Promise<TwitterAccount[]> {
    const args = plainToClass(TwitterAccountFindManyArgs, request.query);
    return this.service.twitterAccounts({
      ...args,
      select: {
        accessToken: true,
        accessTokenSecret: true,
        accountName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TwitterAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async twitterAccount(
    @common.Param() params: TwitterAccountWhereUniqueInput
  ): Promise<TwitterAccount | null> {
    const result = await this.service.twitterAccount({
      where: params,
      select: {
        accessToken: true,
        accessTokenSecret: true,
        accountName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TwitterAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTwitterAccount(
    @common.Param() params: TwitterAccountWhereUniqueInput,
    @common.Body() data: TwitterAccountUpdateInput
  ): Promise<TwitterAccount | null> {
    try {
      return await this.service.updateTwitterAccount({
        where: params,
        data: data,
        select: {
          accessToken: true,
          accessTokenSecret: true,
          accountName: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TwitterAccount })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTwitterAccount(
    @common.Param() params: TwitterAccountWhereUniqueInput
  ): Promise<TwitterAccount | null> {
    try {
      return await this.service.deleteTwitterAccount({
        where: params,
        select: {
          accessToken: true,
          accessTokenSecret: true,
          accountName: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/autoResponses")
  @ApiNestedQuery(AutoResponseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AutoResponse",
    action: "read",
    possession: "any",
  })
  async findAutoResponses(
    @common.Req() request: Request,
    @common.Param() params: TwitterAccountWhereUniqueInput
  ): Promise<AutoResponse[]> {
    const query = plainToClass(AutoResponseFindManyArgs, request.query);
    const results = await this.service.findAutoResponses(params.id, {
      ...query,
      select: {
        aiResponse: true,
        content: true,
        createdAt: true,
        id: true,
        mediaUrl: true,

        trend: {
          select: {
            id: true,
          },
        },

        twitterAccount: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/autoResponses")
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "update",
    possession: "any",
  })
  async connectAutoResponses(
    @common.Param() params: TwitterAccountWhereUniqueInput,
    @common.Body() body: AutoResponseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      autoResponses: {
        connect: body,
      },
    };
    await this.service.updateTwitterAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/autoResponses")
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "update",
    possession: "any",
  })
  async updateAutoResponses(
    @common.Param() params: TwitterAccountWhereUniqueInput,
    @common.Body() body: AutoResponseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      autoResponses: {
        set: body,
      },
    };
    await this.service.updateTwitterAccount({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/autoResponses")
  @nestAccessControl.UseRoles({
    resource: "TwitterAccount",
    action: "update",
    possession: "any",
  })
  async disconnectAutoResponses(
    @common.Param() params: TwitterAccountWhereUniqueInput,
    @common.Body() body: AutoResponseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      autoResponses: {
        disconnect: body,
      },
    };
    await this.service.updateTwitterAccount({
      where: params,
      data,
      select: { id: true },
    });
  }
}
